version: "3.2"
services:
  node:
    image: restaurant:v1.0.0
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=pindB
      
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always    

  mongo:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: mongodb
        target: /bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mongodb:
     driver: local
